#!/usr/bin/env bash

export PATH=".venv/bin:$HOME/.local/share/nvim/mason/bin:$PATH"

function print_formatter {
  echo -e "[1m* $1 *[0m"
  echo
}

if [[ "$1" == "--check" ]]; then
  print_formatter ruff
  ruff format . --check --exclude standalone
  print_formatter stylua
  stylua --check .
  print_formatter luacheck
  luacheck lua/ ftplugin/
else
  print_formatter ruff
  ruff format . --exclude standalone
  print_formatter stylua
  stylua .
fi
