#!/usr/bin/env bash

export PATH=".venv/bin:$HOME/.local/share/nvim/mason/bin:$PATH"

function print_formatter {
  echo -e "\033[1m* $1 *\033[0m"
  echo
}

if [[ "$1" == "--check" ]]; then
  print_formatter ruff
  ruff format . --check
  print_formatter stylua
  stylua --check .
  print_formatter luacheck
  luacheck lua/ ftplugin/
else
  print_formatter ruff
  ruff format .
  print_formatter stylua
  stylua .
fi
