[project]
name = "agent-nvim"
version = "0.1.0"
description = "Neovim Agent Plugin"
requires-python = ">=3.13"
dependencies = [
    "pynvim",
    "openai",
    "openai-agents",
    "hashids",
    "pyzmq",
    "cbor2",
    "html2text",
]

[project.scripts]
anya-daemon = "anya.server.main:main"

[dependency-groups]
dev = [
    "ruff",
]
