local text = [[-- Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ligula nisi, faucibus vel orci quis, faucibus mattis urna. Vivamus malesuada erat nisi. Proin accumsan magna quis orci hendrerit, ac molestie sapien commodo. Suspendisse hendrerit metus vitae diam ullamcorper, nec accumsan metus aliquam. Pellentesque congue, nulla vel porttitor varius, nibh mauris congue justo, et semper ligula ipsum eu arcu. Fusce ac elit non metus egestas vestibulum bibendum sit amet est. Praesent consectetur ex nisl, non scelerisque mi lacinia sed.

-- Morbi sodales auctor velit, sit amet mattis magna venenatis sed. Cras dictum tempus mattis. Aenean et sapien luctus, sodales odio nec, feugiat ante. Integer nec justo neque. Vivamus a enim aliquam, suscipit ex et, suscipit felis. Pellentesque vitae neque et mauris tempor pulvinar. Phasellus ac ornare felis, ac mattis arcu. Quisque tincidunt dolor justo, eget vestibulum eros tincidunt quis. Pellentesque nec est sed nisl rhoncus laoreet. Aliquam blandit lectus a ex finibus, nec scelerisque urna aliquet. Suspendisse semper ex in leo cursus, sit amet ornare eros blandit. Integer turpis enim, viverra id ex id, porta pharetra ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus sit amet blandit erat, et faucibus metus. Quisque feugiat, massa tristique faucibus interdum, mi tortor aliquet ligula, quis mattis mauris metus sed magna. Morbi eu dui rhoncus, vestibulum quam id, dictum quam.

-- Proin sit amet quam id eros convallis efficitur. Donec sed rutrum sem. Proin pulvinar eros massa, non sagittis nibh mattis at. Duis orci lectus, scelerisque id sagittis in, luctus id lorem. Morbi rutrum pellentesque lorem. Etiam dapibus, eros et efficitur tincidunt, mi magna scelerisque dolor, in porttitor arcu tellus at dui. Mauris eget ligula eros. In dignissim sed nulla nec rutrum. Donec faucibus ultrices libero, vel tristique risus volutpat eu. Vestibulum nisl risus, suscipit non augue vel, semper efficitur nulla. Duis eget magna feugiat, egestas mauris vitae, interdum ante. Proin non diam quis ipsum accumsan vulputate at feugiat dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin placerat pellentesque lacus, at dignissim tellus cursus et. Fusce non quam quis dui porttitor efficitur sed id augue. Praesent eget elementum justo.

-- Aliquam elementum malesuada lectus, at posuere magna pharetra id. Proin eleifend elit interdum lorem hendrerit, quis suscipit justo facilisis. Curabitur imperdiet felis eget sem iaculis, sit amet aliquam nunc blandit. In mattis risus eget nunc consequat, a malesuada neque malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque lacus nibh, maximus quis lacus at, fringilla dictum enim. Phasellus mattis non ex at posuere. Praesent non diam sodales, mollis libero sollicitudin, gravida eros.

-- Integer pharetra sagittis libero, eu fermentum tellus viverra id. Sed vehicula vestibulum lobortis. Integer in justo facilisis, condimentum massa nec, commodo arcu. Ut sollicitudin tellus et ex elementum placerat. Phasellus eget nunc pretium, dapibus neque at, aliquet dui. Ut volutpat pulvinar felis, at commodo elit pharetra vitae. Sed quis libero volutpat, dapibus neque eu, sodales erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin fringilla elit id aliquam lacinia. Ut sit amet tincidunt lectus. Nulla a ligula in ipsum imperdiet dictum a ut lectus. Phasellus ut sollicitudin metus. Morbi rutrum fringilla nulla lacinia pretium. Nam euismod dui tristique dapibus molestie.]]

local bufnr = vim.api.nvim_get_current_buf()

vim.fn.AnyaOutputText(text, bufnr, true)

-- vim: wrap


